language: python

before_install:
  - chmod +x ./flaskapp/st.sh

install:
  - pip install Flask==1.1.2
  - pip install gunicorn
  - pip install numpy
  - pip install matplotlib
  - pip install Pillow
  - pip install Flask-WTF

script:
  - cd flaskapp
  - ./st.sh